---
# Copyright 2018 widdix GmbH
# Modification Copyright 2022 unload.sh
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Worker: AWS SQS queue'
Parameters:
  DelaySeconds:
    Description: 'The time in seconds that the delivery of all messages in the queue is delayed'
    Type: Number
    Default: 0
    MinValue: 0
    MaxValue: 900
  MaximumMessageSize:
    Description: 'The limit of how many bytes that a message can contain before Amazon SQS rejects it'
    Type: Number
    Default: 262144
    MinValue: 1024
    MaxValue: 262144
  MessageRetentionPeriod:
    Description: 'The number of seconds that Amazon SQS retains a message'
    Type: Number
    Default: 345600
    MinValue: 60
    MaxValue: 1209600
  ReceiveMessageWaitTimeSeconds:
    Description: "Specifies the duration, in seconds, that the ReceiveMessage action call waits until a message is in the queue in order to include it in the response, as opposed to returning an empty response if a message isn't yet available"
    Type: Number
    Default: 0
    MinValue: 0
    MaxValue: 20
  VisibilityTimeout:
    Description: 'The length of time during which a message will be unavailable after a message is delivered from the queue'
    Type: Number
    Default: 30
    MinValue: 0
    MaxValue: 43200
  MaxReceiveCount:
    Description: 'The number of times a message is delivered to the source queue before being moved to the dead-letter queue'
    Type: Number
    Default: 3
    MinValue: 1
    MaxValue: 1000
Resources:
  Queue:
    Type: 'AWS::SQS::Queue'
    Properties:
      DelaySeconds: !Ref DelaySeconds
      MaximumMessageSize: !Ref MaximumMessageSize
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      ReceiveMessageWaitTimeSeconds: !Ref ReceiveMessageWaitTimeSeconds
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt 'DeadLetterQueue.Arn'
        maxReceiveCount: !Ref MaxReceiveCount
      VisibilityTimeout: !Ref VisibilityTimeout
  DeadLetterQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      MessageRetentionPeriod: 1209600
Outputs:
  Name:
    Value: !GetAtt 'Queue.QueueName'
    Export:
      Name: !Sub '${AWS::StackName}-Name'
  Arn:
    Value: !GetAtt 'Queue.Arn'
    Export:
      Name: !Sub '${AWS::StackName}-Arn'
  Url:
    Value: !Ref Queue
    Export:
      Name: !Sub '${AWS::StackName}-Url'
  Prefix:
    Value: !Sub 'https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}'
    Export:
      Name: !Sub '${AWS::StackName}-Prefix'
